
- name: global name
  git_config:
    name: user.name
    scope: global
    value: "Alex Vyber"
  tags:
  - git

- name: global name
  git_config:
    name: user.name
    scope: global
    value: "Alex Vyber"
  tags:
  - git
