FROM fedora:36 AS base

ARG TAGS
RUN dnf update -y && \
    dnf install -y ansible && \
    dnf install -y curl git


# RUN mkdir /ansible
WORKDIR /ansible

COPY . .

# ENTRYPOINT ["sh", "-c", "ansible-playbook $TAGS local.yml"]

# CMD ["sh", "-c", "/bin/bash"]
